//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersProgramiDeneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersProgrami
    {
        public int ID { get; set; }
        public Nullable<int> GunID { get; set; }
        public Nullable<int> SaatID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> SinifID { get; set; }
    
        public virtual DersTable DersTable { get; set; }
        public virtual GunTable GunTable { get; set; }
        public virtual SaatTable SaatTable { get; set; }
        public virtual SinifTable SinifTable { get; set; }
    }
}
