//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersProgramiDeneme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DersProgramiDbEntities : DbContext
    {
        public DersProgramiDbEntities()
            : base("name=DersProgramiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DersTable> DersTable { get; set; }
        public virtual DbSet<GunTable> GunTable { get; set; }
        public virtual DbSet<SaatTable> SaatTable { get; set; }
        public virtual DbSet<DersProgrami> DersProgrami { get; set; }
        public virtual DbSet<OgretmenTable> OgretmenTable { get; set; }
        public virtual DbSet<SinifTable> SinifTable { get; set; }
    }
}
