//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersProgramiDeneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaatTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaatTable()
        {
            this.DersProgrami = new HashSet<DersProgrami>();
        }
    
        public int ID { get; set; }
        public string Baslangic { get; set; }
        public string Bitis { get; set; }
        public string DersSaatAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersProgrami> DersProgrami { get; set; }
    }
}
